name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit --no-fund
        env:
          NODE_ENV: ci

      - name: Derive base and head SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Lint and Build Affected
        run: npx nx affected --target lint,build

      - name: Test Affected
        run: npx nx affected --target test --configuration ci
